app/nasa_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
# _(''),

from . import settings

urlpatterns = i18n_patterns(
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('users/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('pages.urls', namespace='pages')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/pages/urls.py
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
# _(''),

from . import views, db_test

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path(_('about_us/'), views.AboutView.as_view(), name='about'),

    path(_('projects/'), views.ProjectsListView.as_view(), name='projects'),
    path(_('projects/category') + '/<slug:category_slug>/', views.CategoryProjectListView.as_view(), name='projects_category'),
    path(_('projects') + '/<slug:slug>/', views.ProjectDetailView.as_view(), name='projects_detail'),
    path(_('service/'), views.ServiceListView.as_view(), name='service_list'),
    path(_('service') + '/<slug:slug>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path(_('people/'), views.PeopleListView.as_view(), name='people'),
    path(_('people/category') + '/<slug:category_slug>/', views.CategoryProfileListView.as_view(), name='profile_category'),
    path(_('people') + '/<slug:slug>/', views.ProfileView.as_view(), name='profile'),
    path(_('news/'), views.NewsListView.as_view(), name='news'),
    path(_('news') + '/<slug:slug>/', views.NewsDetailView.as_view(), name='news_detail'),
    path(_('contact/'), views.ContactView.as_view(), name='contact'),
    path(_('contact/success/'), views.SuccessView.as_view(), name='success'),

    path(_('design_elements/'), views.ElementsView.as_view(), name='elements'),
    path(_('design_elements/icons/'), views.IconsView.as_view(), name='elements_icons'),
    path('create_test_data/', db_test.create_test_data, name='create_test_data'),
    path('delete_test_data/', db_test.delete_test_data, name='delete_test_data'),
    path('delete_all_pages_app_data/', db_test.delete_all_data, name='delete_all_pages_app_data'),
    path('delete_all_data/', db_test.delete_all_data, name='delete_all_data'),
]

app/templates/include/bannerbigtop.html
{% load parler_tags %}
{% load static %}
{% load i18n %}
{% load design_tags %}

<!-- start banner Area -->
{% home_big_banner_1840x950 as pic %}
<section class="banner-area relative {% if design.active and design.home_banner_height %} banner_height {% endif %}" id="home" {% if pic.image and pic.active %} style="background:url({{ pic.image.url }}) no-repeat center center" {% endif %}>
    {% if design.active and design.overlay_default %}
        <div class="overlay overlay-bg"></div>
    {% elif design.active and design.overlay %}
        <div class="overlay overlay-bg" style="background-color: {{ design.overlay_color }}; opacity: {{ design.overlay_opacity }};"></div>
    {% else %}
        <div class="overlay overlay-bg"></div>
    {% endif %}
    <div class="container {% if design.active and design.home_banner_text_align_horizontal == 'ttl' %} ctl {% elif design.home_banner_text_align_horizontal == 'ttr' %} ctr lll {% endif %}">
        {% if design.active %}
            {% if design.home_banner_text_align_vertical %}
                <div class="row fullscreen no-padding no-margin {{ design.home_banner_text_align_horizontal }}  {{ design.home_banner_text_align_vertical }}">
                    <div class="banner-content col-lg-9 col-md-12 no-padding no-margin ttt ttb {{ design.home_banner_text_align_horizontal }}" >
                        {% home_texts as texts %}
                        {% if texts.active %}
                            {% if texts|get_translated_field:'banner_big_text' or texts|get_translated_field:'small_page_title' %}
                                {% with texts|get_translated_field:'banner_big_text' as big %}
                                    <h1 class="mb-10 banner-title-style">{{ big|safe }}</h1>

                                {% endwith %}
                                {% with texts|get_translated_field:'small_page_title' as small %}
                                    <div class="small_title-style">{{ small|safe }}</div>
                                {% endwith %}

                                {% if design|get_translated_field:'home_big_banner_button' %}
                                    <a href="{% url 'pages:contact' %}" class="genric-btn {{ design.get_button }} text-uppercase mt-10">{{ design|get_translated_field:'home_big_banner_button' }} {% if 'arrow' in design.button_form %}<span class="lnr lnr-arrow-right"></span>{% endif %}</a>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            {% endif %}

        {% else %}
            <div class="row fullscreen d-flex justify-content-center align-items-center">
                <div class="banner-content col-lg-9 col-md-12 justify-content-center ">
                    {% home_texts as texts %}
                    {% design_settings as design %}
                    {% if texts.active %}
                        {% if texts|get_translated_field:'banner_big_text' or texts|get_translated_field:'small_page_title' %}
                            {% with texts|get_translated_field:'banner_big_text' as big %}
                                <h1 class="mb-10 title-size">{{ big|safe }}</h1>
                            {% endwith %}
                            {% with texts|get_translated_field:'small_page_title' as small %}
                                <p class="text-white mx-auto title-size">{{ small|safe }}</p>
                            {% endwith %}

                            {% if design %}
                                {% if design|get_translated_field:'home_big_banner_button' %}
                                    <a href="{% url 'pages:contact' %}" class="genric-btn header-btn text-uppercase mt-10 button_text_style {{ design.get_button_style }}">{{ design|get_translated_field:'home_big_banner_button' }}</a>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
</section>
<!-- End banner Area -->

app/templates/include/bannertop.html
{% extends '_base.html' %}

{% load static %}
{% load i18n %}
{% load design_tags %}

{#    {% include 'include/bannertop.html' %}#}

{##}
{#{% top_banner_1840x300 as pic %}#}
{##}
{#<section class="banner-area relative" id="home" {% if pic.image and pic.active or design.banner_height %} style="background:url({{ pic.image.url }}) no-repeat center center; {% if design.banner_height %}height: {{ design.banner_height }}px{% endif %}" {% endif %}>#}
{#    {% if design.overlay %} <div class="overlay overlay-bg" style="background-color: {{ design.overlay_color }}; opacity: {{ design.overlay_opacity }};"></div> {% endif %}#}
{#    <div class="container">#}
{#        <div class="row d-flex align-items-center justify-content-center">#}
{#            <div class="about-content col-lg-12">#}
{#                <h1 class="text-white">#}
{#                    {% block title2 %}#}
{##}
{#                    {% endblock title2 %}#}
{#                </h1>#}
{##}
{#                {% block top %}#}
{#                {% endblock top %}#}
{##}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</section>#}

app/templates/include/callto-action.html
{% load parler_tags %}
{% load static %}
{% load i18n %}
{% load design_tags %}

<!-- Start callto-action Area -->
<section class="callto-action-area pt-50 pb-10">
    <div class="container">
        <div class="row justify-content-center ">
            {% home_call_to_banner_1110x350 as pic %}
            <div class="callto-action-wrap col-lg-12 relative section-gap" {% if pic.image %} style='background:-webkit-linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)),url({{ pic.image.url }}) no-repeat center ' {% endif %}>
{#            background:-webkit-linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)),url(../../media/images/defaults/call-action-bg.jpg)  media/images/news.jpg#}
                <div class="content pt-40 pb-0 text-center">
                    {% home_callto_texts as texts %}
                    {% if texts.active %}
                        {% if texts|get_translated_field:'big_page_title' or texts|get_translated_field:'small_page_title' %}
                            {% with texts|get_translated_field:'big_page_title' as big %}
                                <h1 class="mb-10 big-title-style">{{ big|safe }}</h1>

                            {% endwith %}
                            {% with texts|get_translated_field:'small_page_title' as small %}
                                <div class="small-title-style mx-auto">{{ small|safe }}</div>
                            {% endwith %}

                            {% if design|get_translated_field:'callto_banner_button_text' %}
                                <a href="{% url 'pages:contact' %}" class="genric-btn {{ design.get_button }} text-uppercase mt-10 button_text_style">{{ design|get_translated_field:'callto_banner_button_text' }} {% if 'arrow' in design.button_form %}<span class="lnr lnr-arrow-right"></span>{% endif %}</a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End callto-action Area -->

app/templates/include/footer.html
{% load parler_tags %}
{% load static %}
{% load page_tags %}
{% load i18n %}
{% load design_tags %}

<!-- start footer Area -->
<footer class="footer-area section-gap mt-0 pt-0 {% if design.active and design.footer_background_color %} footer-bg-color {% elif design.active and design.background_color %} bg-color {% endif %}">
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-6 col-sm-6 mt-0 pt-0">
                <div class="single-footer-widget font">
                    {% footer_texts as texts %}
                    {% if texts.active %}
                        {% if texts|get_translated_field:'big_page_title' %}
                            {% with texts|get_translated_field:'big_page_title' as big %}
                                <h6><a href="{% url 'pages:about' %}" class="big-title-style">{{ big|safe }}</a></h6>
                            {% endwith %}
                        {% endif %}
                        {% if texts|get_translated_field:'small_page_title' %}
                            {% with texts|get_translated_field:'small_page_title' as small %}
                                <div class="footer-text-style">{{ small|safe }}</div>
                            {% endwith %}
                        {% endif %}
                    {% else %}
                        <h6 class="big-title-style"><a href="{% url 'pages:about' %}" >{% trans 'About Us' %}</a></h6>
                    {% endif %}

                    <div class="footer-text-style"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Webapp is made by <a href="https://vsdemo.ee"> VS OU</a> | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>

                </div>
            </div>
            {% company as contacts %}
            {% if contacts.active %}
                <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                    <div class="single-footer-widget">
                        {% if contacts.facebook or contacts.instagram or contacts.twitter %}
                            <h6 class="big-title-style">{% trans 'Follow Us' %}</h6>
                            <div class="footer-text-style">Let us be social</div>
                            <div class="footer-social d-flex align-items-center ">
                                {% if contacts.facebook %}
                                    <a href="{{ contacts.facebook }}" target="_blank"><i class="fa fa-facebook" ></i></a>
                                {% endif %}
                                {% if contacts.instagram %}
                                    <a href="{{ contacts.instagram }}" target="_blank"><i class="fa fa-instagram"></i></a>
                                {% endif %}
                                {% if contacts.twitter %}
                                    <a href="{{ contacts.twitter }}" target="_blank"><i class="fa fa-twitter"></i></a>
                                {% endif %}
                            </div>
                        {% else %}
                            <h6> </h6>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                    <div class="single-footer-widget">
                        <h6><a href="{% url 'pages:contact' %}" class="big-title-style">{% trans 'Contact Us' %}</a></h6>
                        <a href="tel:{{ contacts.phone_number }}" class="footer-text-style">{{ contacts.phone_number }}</a>
                        <a href="mailto:{{ contacts.email }}" class="footer-text-style">{{ contacts.email }}</a>
                    </div>
                </div>
            {% else %}
                <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                    <div class="single-footer-widget">
                        <h6><a href="{% url 'pages:contact' %}" class="big-title-style">{% trans 'Contact Us' %}</a></h6>
                        <a href="tel:+372 506 5668" class="footer-text-style">+372 555 5665</a>
                        <a href="mailto:info@nasa.ee" class="footer-text-style">info@default.ee</a>
                    </div>
                </div>
            {% endif %}

        </div>
    </div>
</footer>
<!-- End footer Area -->

app/templates/include/gallery.html
{% load parler_tags %}
{% load static %}
{% load i18n %}
{% load design_tags %}

<!-- Start gallery Area -->
<section class="gallery-area pt-60">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-12 pb-40 header-text text-center">
                {% project_list_texts as texts %}
                {% if texts.active %}
                    {% if texts|get_translated_field:'big_page_title' or texts|get_translated_field:'small_page_title' %}
                        <a href="{% url 'pages:projects' %}">
                            {% with texts|get_translated_field:'big_page_title' as big %}
                                <h1 class="mb-10 big-title-style">{{ texts.big_page_title|safe }}</h1>
                            {% endwith %}
                        </a>
                            {% with texts|get_translated_field:'small_page_title' as small %}
                                <p>{{ small|safe }}</p>
                            {% endwith %}

                    {% endif %}
                {% else %}
                    <a href="{% url 'pages:projects' %}">
                        <h1 class="pb-10">{% trans 'Our Recent Works may impress you' %}</h1>
                    </a>
                {% endif %}

            </div>
        </div>
        <div class="row">
            {% if hprojects.0 %}
                {% with hprojects.0 as project %}
                    {% include 'include/pages/projects8.html' %}
                {% endwith %}
            {% endif %}
            {% if hprojects.1 %}
                {% with hprojects.1 as project %}
                    {% include 'include/pages/projects4.html' %}
                {% endwith %}
            {% endif %}
        </div>
        <div class="row">
            {% if hprojects.2 %}
                {% with hprojects.2 as project %}
                    {% include 'include/pages/projects4.html' %}
                {% endwith %}
            {% endif %}
            {% if hprojects.3 %}
                {% with hprojects.3 as project %}
                    {% include 'include/pages/projects8.html' %}
                {% endwith %}
            {% endif %}
        </div>
    </div>
</section>
<!-- End gallery Area -->

app/templates/include/header.html
{% load thumbnail %}
{% load static %}
{% load page_tags design_tags %}
{% load i18n parler_tags %}

<header id="header" id="home">

    <div class="header-top" >
        <div class="container" {% if design.active and not design.full_top_banner %} style="padding-right: 3%; padding-left: 3%; padding-top: 3%" {% endif %}>
            <div class="row" style="margin-top: 5px">
                {% company as contacts %}
                {% if contacts.active %}

                    <div class="col-lg-4 col-sm-4 col-4 header-top-left no-padding ">
                        {% if contacts.phone_number %} <a href="tel:{{ contacts.phone_number }}">{{ contacts.phone_number }}</a> {% endif %}
                        {% if contacts.email %} <a href="mailto:{{ contacts.email }}">{{ contacts.email }}</a> {% endif %}
                    </div>
{#                    <div class="col-lg-4 col-sm-4 col-4 header-top-right no-padding float-right">#}
{#                        <ul class="nav-menu float-right">#}
{#                            {% if request.user.is_authenticated and request.user.is_superuser %}#}
{#                                <li><a href="{% url 'pages:elements' %}"> {% trans 'Other Design Elements' %}</a></li>#}
{#                            {% endif %}#}
{##}
{#                            {% if request.user.is_authenticated and request.user.is_superuser %}#}
{#                                <li><a href="{% url 'pages:elements' %}"> {% trans 'Other Design Elements' %}</a></li>#}
{#                            {% else %}#}
{#                                 <li></li>#}
{#                            {% endif %}#}
{##}
{#                            {% if contacts.facebook %}#}
{#                                <li class="social-icons-top"><a href="{{ contacts.facebook }}" target="_blank"><i class="fa fa-facebook"></i></a></li>#}
{#                            {% endif %}#}
{#                            {% if contacts.instagram %}#}
{#                                <li class="social-icons-top"><a href="{{ contacts.instagram }}" target="_blank"><i class="fa fa-instagram"></i></a></li>#}
{#                            {% endif %}#}
{#                            {% if contacts.twitter %}#}
{#                                <li class="social-icons-top"><a href="{{ contacts.twitter }}" target="_blank"><i class="fa fa-twitter"></i></a></li>#}
{#                            {% endif %}#}
{##}
{#                            {% get_current_language as cur_lang %}#}
{#                            {% get_available_languages as langs %}#}
{#                            {% get_language_info_list for langs as languages %}#}
{##}
{#                        </ul>#}
{#                            <nav id="nav-menu-container" class="nav-menu">#}
{##}
{##}
{#                                {% for language in languages %}#}
{#                                    {% get_translated_url cur_lang as tr_url %}#}
{#                                    <a href="/{{ language.code }}/">#}
{#                                        {{ language.name_translated }}#}
{#                                    </a>#}
{#                                {% endfor %}#}
{##}
{##}
{#                            </nav>#}
{##}
{##}
{#                    </div>#}
{##}
                {% else %}

                    <div class="col-lg-4 col-sm-4 col-4 header-top-left no-padding">
                        <a href="tel:+372 506 5668">+372 555 5665</a>
                        <a href="mailto:info@nasa.ee">info@default.ee</a>
                    </div>
{#                    <div class="col-lg-4 col-sm-4 col-4 header-top-right no-padding"></div>#}
                {% endif %}

                <div  class="col-lg-8 col-sm-8 col-8 header-top-right no-padding">
                    <nav id="nav-menu-container row">
                        <ul class="nav-menu float-right">
{#                            <li>#}
                                {% get_current_language as cur_lang %}
                                {% get_available_languages as langs %}
                                {% get_language_info_list for langs as languages %}


                                {% for language in languages %}
                                    {% get_translated_url cur_lang as tr_url %}
                                    <li>
                                        <a href="/{{ language.code }}/">
                                            {{ language.name_translated }}
                                        </a>
                                    </li>

                                {% endfor %}
{#                            </li>#}

                        </ul>
                    </nav>
                    <nav id="nav-menu-container row">
                        <ul class="nav-menu float-right">
                            {% if request.user.is_authenticated and request.user.is_staff %}
                                <li><a href="{% url 'pages:elements' %}"> {% trans 'Other Design Elements' %}</a></li>
                            {% else %}
                                 <li></li>
                            {% endif %}

                            {% if contacts.active %}
                                {% if contacts.facebook %}
                                    <li class="social-icons-top"><a href="{{ contacts.facebook }}" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                {% endif %}
                                {% if contacts.instagram %}
                                    <li class="social-icons-top"><a href="{{ contacts.instagram }}" target="_blank"><i class="fa fa-instagram"></i></a></li>
                                {% endif %}
                                {% if contacts.twitter %}
                                    <li class="social-icons-top"><a href="{{ contacts.twitter }}" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                {% endif %}
                            {% endif %}
                        </ul>

                    </nav>
                </div>


            </div>
        </div>
    </div>
    <div class="container main-menu" {% if design.active and not design.full_top_banner %} style="padding-right: 3%; padding-left: 3%" {% endif %}>

        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                {% company as contacts %}
                {% logo_size as size %}
                {% if contacts.active %}
                    {% if contacts.logo %}
                        <a href="{% url 'pages:home' %}">
                            {% thumbnail contacts.logo size crop='center' as logo %}
                                <img class="img-fluid d-block mx-auto" src="{{ logo.url }}" height="30" alt="">
                            {% endthumbnail %}
                        </a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'pages:home' %}"><img src="{%  static 'img/logo.png' %}" alt="" title="" /></a>
                {% endif %}
            </div>

            <nav id="nav-menu-container" >
                <ul class="nav-menu" >
                    <li class="menu-active"><a href="{% url 'pages:home' %}">{% trans 'HOME' %}</a></li>
                    {% category_settings as category_set %}
                    {% if category_set.project_category %}
                        <li class="menu-has-children"><a href="{% url 'pages:projects' %}">{% trans 'PROJECTS' %}</a>
                            <ul>
                                <li><a href="{% url 'pages:projects' %}">{% trans 'All Projects' %}</a></li>
                                {% project_categories as project_categories %}
                                    {% for category in project_categories %}
                                        <li><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></li>
                                    {% endfor %}
                            </ul>
                        </li>
                    {% else %}
                        <li ><a href="{% url 'pages:projects' %}">{% trans 'PROJECTS' %}</a>
                    {% endif %}
                    {% if category_set.profile_category %}
                        <li class="menu-has-children"><a href="{% url 'pages:people' %}">{% trans 'PEOPLE' %}</a>
                            <ul>
                                <li><a href="{% url 'pages:people' %}">{% trans 'All People' %}</a></li>
                                {% profile_categories as profile_categories %}
                                    {% for category in profile_categories %}
                                        <li><a href="{{ category.get_absolute_url }}">{{ category.title }}</a></li>
                                    {% endfor %}
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'pages:people' %}">{% trans 'PEOPLE' %}</a>
                    {% endif %}

                    <li><a href="{% url 'pages:service_list' %}">{% trans 'SERVICES' %}</a></li>
                    <li><a href="{% url 'pages:news' %}">{% trans 'NEWS' %}</a></li>


    {#              <li class="menu-has-children"><a href="">Pages</a>#}
    {#                <ul>#}
    {#                    <li><a href="project-details.html">Project Details</a></li>#}
    {#                    <li><a href="elements.html">Elements</a></li>#}
    {#                    <li class="menu-has-children"><a href="">Level 2 </a>#}
    {#                        <ul>#}
    {#                            <li><a href="#">Item One</a></li>#}
    {#                            <li><a href="#">Item Two</a></li>#}
    {#                        </ul>#}
    {#                    </li>#}
    {#                </ul>#}
    {#              </li>#}
                    <li><a href="{% url 'pages:about' %}">{% trans 'About Us' %}</a></li>
                    <li><a href="{% url 'pages:contact' %}">{% trans 'CONTACT' %}</a></li>



                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </div>

    <script>
        let lang1 = {{ langs.0 }};
        let lang2 = {{ langs.1 }};
        let lang3 = {{ langs.2 }};

    </script>
</header><!-- #header -->

app/templates/include/news.html
{% load parler_tags %}
{% load thumbnail %}
{% load static %}
{% load i18n %}
{% load design_tags %}

<!-- Start blog Area -->
{% if hnews %}
    <section class="blog-area section-gap mb-5 pb-10">
        <div class="container mb-0 pb-0">
            <div class="row d-flex justify-content-center">
                <div class="menu-content pb-10 pt-60 col-lg-9">
                    <div class="title text-center">
                        {% news_list_texts as texts %}
                        {% if texts.active %}
                            {% if texts|get_translated_field:'big_page_title' or texts|get_translated_field:'small_page_title' %}
                                <a href="{% url 'pages:news' %}">
                                    {% with texts|get_translated_field:'big_page_title' as big %}
                                        <h1 class="mb-10 big-title-style">{{ texts.big_page_title|safe }}</h1>
                                    {% endwith %}
                                </a>
                                    {% with texts|get_translated_field:'small_page_title' as small %}
                                        <div class="small-text-title">{{ small|safe }}</div>
                                    {% endwith %}
                            {% endif %}
                        {% else %}
                            <a href="{% url 'pages:news' %}">
                                <h1 class="mb-10 big-title-style">{% trans 'News' %}</h1>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="active-blog-carusel">
                    {% for item in hnews %}
                        <div class="single-blog-post item">
                            <a href="{{ item.get_absolute_url }}">
                                <div class="thumb">
                                    {% thumbnail item.image "350x250" crop='center' as img %}
                                        <img class="content-image img-fluid d-block mx-auto" style="border-radius: 10px" src="{{ img.url }}" height="250" alt="">
                                    {% endthumbnail %}
                                </div>
                                <div class="details">
        {#                            <div class="tags">#}
        {#                                <ul>#}
        {#                                    <li>#}
        {#                                        <a href="#">Travel</a>#}
        {#                                    </li>#}
        {#                                    <li>#}
        {#                                        <a href="#">Life Style</a>#}
        {#                                    </li>#}
        {#                                </ul>#}
        {#                            </div>#}
                                    <h4 class="title small-text-title">{{ item.title }}</h4>
                                    <p class="pb-10 date-style" >{{ item.published }}</p>
                                    <p>
                                        {{ item.short_description|safe }}
                                    </p>

                                </div>
                            </a>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </section>
{% endif %}
<!-- End blog Area -->