app/nasa_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
# _(''),

from . import settings

urlpatterns = i18n_patterns(
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('users/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('rosetta/', include('rosetta.urls')),
    path('', include('pages.urls', namespace='pages')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/pages/urls.py
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
# _(''),

from . import views, db_test

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path(_('about_us/'), views.AboutView.as_view(), name='about'),

    path(_('projects/'), views.ProjectsListView.as_view(), name='projects'),
    path(_('projects/category') + '/<slug:category_slug>/', views.CategoryProjectListView.as_view(), name='projects_category'),
    path(_('projects') + '/<slug:slug>/', views.ProjectDetailView.as_view(), name='projects_detail'),
    path(_('service/'), views.ServiceListView.as_view(), name='service_list'),
    path(_('service') + '/<slug:slug>/', views.ServiceDetailView.as_view(), name='service_detail'),
    path(_('people/'), views.PeopleListView.as_view(), name='people'),
    path(_('people/category') + '/<slug:category_slug>/', views.CategoryProfileListView.as_view(), name='profile_category'),
    path(_('people') + '/<slug:slug>/', views.ProfileView.as_view(), name='profile'),
    path(_('news/'), views.NewsListView.as_view(), name='news'),
    path(_('news') + '/<slug:slug>/', views.NewsDetailView.as_view(), name='news_detail'),
    path(_('contact/'), views.ContactView.as_view(), name='contact'),
    path(_('contact/success/'), views.SuccessView.as_view(), name='success'),

    path(_('design_elements/'), views.ElementsView.as_view(), name='elements'),
    path(_('design_elements/icons/'), views.IconsView.as_view(), name='elements_icons'),
    path('create_test_data/', db_test.create_test_data, name='create_test_data'),
    path('delete_test_data/', db_test.delete_test_data, name='delete_test_data'),
    path('delete_all_pages_app_data/', db_test.delete_all_data, name='delete_all_pages_app_data'),
    path('delete_all_data/', db_test.delete_all_data, name='delete_all_data'),
]

app/pages/models.py
import datetime
from datetime import date

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from parler.utils.context import smart_override, switch_language
from parler.utils.i18n import get_language
from phonenumber_field.modelfields import PhoneNumberField
from django.template.defaultfilters import truncatewords

from django.utils.translation import gettext_lazy as _
from parler.models import TranslatableModel, TranslatedFields, TranslatedFieldsModelMixin
# _(''),


def group(iterable, mycount):
    it = len(list(iterable))
    a = list(zip(*[iter(iterable)] * mycount))
    b = len(a) * mycount
    c = it - b
    if c > 0:
        a.append(list(list(iterable)[-c:]))
    return a


class Service(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=200, unique=True, db_index=True),
        slug=models.SlugField(_('slug'), max_length=200, unique=True, blank=True, null=True, db_index=True),
        short_description=RichTextUploadingField(_('short_description')),
        description=RichTextUploadingField(_('description'), blank=True, null=True),

    )
    image = models.ImageField(_('news image'), upload_to='images/services/', default='images/defaults/news.jpg', blank=True, null=True)

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            if len(self.title) < 15:
                self.slug = slugify(self.title)
            else:
                self.slug = slugify(truncatewords(self.title, 3))
        super(Service, self).save(*args, **kwargs)

    def get_absolute_url(self):
        with switch_language(self):
            return reverse('pages:service_detail', kwargs={'slug': self.slug})


class ProfileCategory(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=200, unique=True, db_index=True),
        category_slug=models.SlugField(_('category_slug'), db_index=True, max_length=200, unique=True, blank=True, null=True),
    )

    class Meta:
        # ordering = ['title']
        verbose_name = _('Profile Category')
        verbose_name_plural = _('Profile Categories')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.category_slug:
            if len(self.title) < 15:
                self.category_slug = slugify(self.title)
            else:
                self.category_slug = slugify(truncatewords(self.title, 3))
        super(ProfileCategory, self).save(*args, **kwargs)

    def get_absolute_url(self):
        with switch_language(self):
            return reverse('pages:profile_category', kwargs={'category_slug': self.category_slug, })


class Profile(TranslatableModel):
    translations = TranslatedFields(
        first_name=models.CharField(_('first name'), max_length=200),
        last_name=models.CharField(_('last name'), max_length=200),
        slug=models.SlugField(_('slug'), max_length=200, unique=True, blank=True, null=True, db_index=True),
        short_description=RichTextUploadingField(_('short_description')),
        description=RichTextUploadingField(_('description'), blank=True, null=True),
    )

    profile_category = models.ManyToManyField(ProfileCategory, blank=True, default=None, related_name='profile_category')
    facebook = models.URLField(_('facebook'), max_length=200, blank=True, null=True)
    twitter = models.URLField(_('twitter'), max_length=200, blank=True, null=True)
    phone_number = PhoneNumberField(_('phone number'), blank=True, null=True)
    email = models.EmailField(_('email'), blank=True, null=True)
    start_work = models.DateField(_('start_work'), default=timezone.now)

    image = models.ImageField(_('profile image'), upload_to='images/profile/', default='images/defaults/project-details.jpg')

    class Meta:
        # ordering = ['start_work']
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def get_name(self):
        return '%s %s' % (self.safe_translation_getter("first_name", language_code="en"), self.safe_translation_getter("last_name", language_code="en"))

    def __str__(self):
        return self.get_name()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.get_name())
        super(Profile, self).save(*args, **kwargs)

    # def get_absolute_url(self):
    #     return reverse('pages:profile', kwargs={'slug': self.slug})
    def get_absolute_url(self):
        with switch_language(self):
            return reverse('pages:profile', kwargs={'slug': self.slug})

    def get_short_description(self):
        desc = truncatewords(self.short_description, 25) + '...'
        return desc


class News(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=200, unique=True, db_index=True),
        slug=models.SlugField(_('slug'), max_length=200, unique=True, blank=True, null=True, db_index=True),
        short_description=RichTextUploadingField(_('short_description'), ),
        description=RichTextUploadingField(_('description'), blank=True, null=True),
    )
    image = models.ImageField(_('news image'), upload_to='images/news/', default='images/defaults/news.jpg')
    published = models.DateField(_('published'), default=datetime.date.today)

    class Meta:
        # ordering = ['-published']
        verbose_name = _('News')
        verbose_name_plural = _('News')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if len(self.title) < 15:
            self.slug = slugify(self.title)
        else:
            self.slug = slugify(truncatewords(self.title, 3))
        super(News, self).save(*args, **kwargs)

    def get_absolute_url(self):
        with switch_language(self):
            return reverse('pages:news_detail', kwargs={'slug': self.slug, })


class ProjectCategory(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_('title'), max_length=200, unique=True, db_index=True),
        category_slug=models.SlugField(_('category_slug'), db_index=True, max_length=200, unique=True, blank=True, null=True)
    )

    class Meta:
        # ordering = ['title']
        verbose_name = _('Project Category')
        verbose_name_plural = _('Project Categories')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.category_slug:
            if len(self.title) < 15:
                self.category_slug = slugify(self.title)
            else:
                self.category_slug = slugify(truncatewords(self.title, 3))
        super(ProjectCategory, self).save(*args, **kwargs)

    def get_absolute_url(self):
        with switch_language(self):
            return reverse('pages:projects_category', kwargs={'category_slug': self.category_slug, })


class Project(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(_('title'), db_index=True, max_length=200, unique=True),
        slug=models.SlugField(_('slug'), db_index=True, max_length=200, unique=True, blank=True, null=True),
        short_description=RichTextUploadingField(_('short_description'), ),
        description=RichTextUploadingField(_('description'), blank=True, null=True),
    )

    project_category = models.ManyToManyField(ProjectCategory, blank=True, default=None, related_name='project_category')
    project_team = models.ManyToManyField(Profile, blank=True, default=None, related_name='projects')
    client = models.CharField(_('client'), max_length=200, blank=True, null=True)
    website = models.URLField(_('website'), max_length=200, blank=True, null=True)
    completed = models.DateField(_('completed'), default=timezone.now)
    first_image = models.ImageField(_('first_image'), upload_to='images/projects/', default='images/defaults/project-details.jpg')
    index = models.PositiveSmallIntegerField(blank=True, null=True, default=0)

    class Meta:
        # ordering = ['-completed']
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            if len(self.title) < 15:
                self.slug = slugify(self.title)
            else:
                self.slug = slugify(truncatewords(self.title, 3))
        super(Project, self).save(*args, **kwargs)

    def get_absolute_url(self):
        with switch_language(self):
            return reverse('pages:projects_detail', kwargs={'slug': self.slug})

    def get_images(self):
        project = Project.objects.language('en').get(translations__slug=self.slug)
        img = ProjectImage.objects.filter(project__id=project.id)
        return group(img, 4)


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, default=None, on_delete=models.CASCADE, related_name='image')
    image = models.ImageField(_('project image'), upload_to='images/projects/', default='/images/defaults/project-details.jpg')
    index = models.PositiveSmallIntegerField(blank=True, null=True, default=0)

    class Meta:
        ordering = ['index']
        verbose_name = _('Project Image')
        verbose_name_plural = _('Project Images')

app/templates/pages/about.html
{% extends 'base.html' %}
{% load parler_tags %}

{% load static %}
{% load i18n %}
{% load design_tags %}

{% block title %}
    {% about_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'browser_title' %}
            {% with texts|get_translated_field:'browser_title' as titl %}
                {{ titl|safe }}
            {% endwith %}
        {% else %}
            {% trans 'About Us' %}
        {% endif %}
    {% else %}
        {% trans 'About Us' %}
    {% endif %}
{% endblock title %}

{% block title2 %}
    {% about_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'banner_big_text' %}
            {% with texts|get_translated_field:'banner_big_text' as titl %}
                <h1 class="banner-title-style">{{ titl|safe }}</h1>
            {% endwith %}
        {% endif %}
    {% else %}
        <h1 class="banner-title-style"> {% trans 'About Us' %} </h1>
    {% endif %}
{% endblock title2 %}

{% block top %}
    {% design_settings as design %}
    {% if design.active and design.top_navigation %}
        <p class="link-nav">
            <a href="{% url 'pages:home' %}"> {% trans 'Home' %} </a>
            <span class="lnr lnr-arrow-right"></span>
            <a href="{% url 'pages:about' %}"> {% trans 'About Us' %} </a>
        </p>
    {% endif %}
{% endblock top %}

{% block conteiner %}

    <!-- Start about-video Area -->
    <section class="about-video-area section-gap">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-20 header-text text-center">
                    {% about_texts as texts %}
                    {% if texts.active %}
                        {% if texts|get_translated_field:'big_page_title' or texts|get_translated_field:'small_page_title' %}
                            {% with texts|get_translated_field:'big_page_title' as big %}
                                <h1 class="mb-10 big-title-style">{{ texts.big_page_title|safe }}</h1>
                            {% endwith %}
                            {% with texts|get_translated_field:'small_page_title' as small %}
                                <div class="small-title-style">{{ small|safe }}</div>
                            {% endwith %}

                            {% with texts|get_translated_field:'add_other_text' as other %}
                                <p class="mt-20">{{ other|safe }}</p>
                            {% endwith %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!-- End about-video Area -->

    <section class="gallery-area pt-40">
        <div class="container">
            {% include 'include/callto-action.html' %}

            {% include 'include/feature.html' %}
            {% include 'include/service.html' %}
            {% include 'include/testimonial.html' %}

            {% include 'include/team.html' %}
            {% include 'include/news.html' %}
            {% include 'include/brands.html' %}
        </div>
    </section>

{% endblock conteiner %}

app/templates/pages/news_detail.html
{% extends 'base.html' %}
{% load parler_tags %}
{% load thumbnail %}

{% load static %}
{% load i18n %}
{% load design_tags %}

{% block title %}
    {% news_detail_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'browser_title' %}
            {% with texts|get_translated_field:'browser_title' as titl %}
                {{ titl|safe }} {% if texts.add_name %} "{{ news.title }}"  {% endif %}
            {% endwith %}
        {% else %}
            {% trans 'News' %} {% if texts.add_name %} "{{ news.title }}"  {% endif %}
        {% endif %}
    {% else %}
        {% trans 'News' %}
    {% endif %}
{% endblock title %}

{% block title2 %}
    {% news_detail_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'banner_big_text' %}
            {% with texts|get_translated_field:'banner_big_text' as titl %}
                <h1 class="banner-title-style">{{ titl|safe }} {% if texts.add_name %} "{{ news.title }}" {% endif %}</h1>
            {% endwith %}
        {% endif %}
    {% else %}
        <h1 class="banner-title-style"> {% trans 'News' %} </h1>
    {% endif %}
{% endblock title2 %}

{% block top %}
    {% design_settings as design %}
    {% if design.top_navigation %}
        <p class="text-white link-nav">
            <a href="{% url 'pages:home' %}"> {% trans 'Home' %} </a>
            <span class="lnr lnr-arrow-right"></span>
            <a href="{% url 'pages:news' %}"> {% trans 'News' %} </a>
        </p>
    {% endif %}
{% endblock top %}

{% block conteiner %}
    <section class="service-area section-gap" id="service">
        <div class="container">
{#            <h1 class="mb-50 text-center">{{ news.title }}</h1>#}
            <div class="justify-content-center">
                <div class="col-md-12 pb-50 header-text text-center">
                    <h1 class="mb-10 big-title-style">{{ news.title }}</h1>
                    {% news_detail_texts as texts %}
                    {% if texts.active %}
                        {% if texts|get_translated_field:'small_page_title' %}
                            {% with texts|get_translated_field:'small_page_title' as small %}
                                <div class="small-title-style">{{ small|safe }}</div>
                            {% endwith %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-12 justify-content-center">
                {% with news.image as image %}
                    {% if image %}
                        {% thumbnail image "1000x400" crop='center' as img %}
                            <img class="img-fluid d-block mx-auto" style="border-radius: 10px"  src="{{ img.url }}" width="1030" alt="">
                        {% endthumbnail %}
                    {% endif %}
                {% endwith %}
            </div>
            <div class="section-top-border p-4">
                <div class="row">
                    <div class="col-lg-12">
                        <blockquote class="generic-blockquote">
                            <p class="date-style">{{ news.published }}</p>
                            <p class="main-style">{{ news.short_description|safe }}</p>
                            <p class="main-style">{{ news.description|safe }}</p>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock conteiner %}

app/templates/pages/news_list.html
{% extends 'base.html' %}
{% load parler_tags %}

{% load static %}
{% load i18n %}
{% load design_tags %}

{% block title %}
    {% news_list_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'browser_title' %}
            {% with texts|get_translated_field:'browser_title' as titl %}
                {{ titl|safe }}
            {% endwith %}
        {% else %}
            {% trans 'News' %}
        {% endif %}
    {% else %}
        {% trans 'News' %}
    {% endif %}
{% endblock title %}

{% block title2 %}
    {% news_list_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'banner_big_text' %}
            {% with texts|get_translated_field:'banner_big_text' as titl %}
                <h1 class="banner-title-style">{{ titl|safe }}</h1>
            {% endwith %}
        {% endif %}
    {% else %}
        <h1 class="banner-title-style"> {% trans 'News' %} </h1>
    {% endif %}
{% endblock title2 %}

{% block top %}
    {% design_settings as design %}
    {% if design.top_navigation %}
        <p class="text-white link-nav">
            <a href="{% url 'pages:home' %}"> {% trans 'Home' %} </a>
            <span class="lnr lnr-arrow-right"></span>
            <a href="{% url 'pages:news' %}"> {% trans 'News' %} </a>
        </p>
    {% endif %}
{% endblock top %}

{% block conteiner %}

    <!-- Start service Area -->
    <section class="service-area section-gap" id="service">
        <div class="container">
            <div class="justify-content-center">
                <div class="col-md-12 pb-50 header-text text-center">
                    {% news_list_texts as texts %}
                    {% if texts.active %}
                        {% if texts|get_translated_field:'big_page_title' or texts|get_translated_field:'small_page_title' %}
                            {% with texts|get_translated_field:'big_page_title' as big %}
                                <h1 class="mb-10 big-title-style">{{ texts.big_page_title|safe }}</h1>
                            {% endwith %}
                            {% with texts|get_translated_field:'small_page_title' as small %}
                                <div class="small-title-style">{{ small|safe }}</div>
                            {% endwith %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            {% for page in news_list %}
                <a href="{{ page.get_absolute_url }}">
                    <div class="section-top-border p-4">
                        <h3 class="mb-10 main-style">{{ page.title }}</h3>
                        <div class="row">
                            <div class="col-lg-12">
                                <blockquote class="generic-blockquote">
                                    <p class="date-style">{{ page.published }}</p>
                                    <p class="main-style">{{ page.short_description|safe }}</p>
                                </blockquote>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
            {% include 'include/pagination.html' %}
        </div>
    </section>
    <!-- End service Area -->

{% endblock conteiner %}

app/templates/pages/projects_list.html
{% extends 'base.html' %}
{% load parler_tags %}

{% load static %}
{% load page_tags %}
{% load thumbnail %}
{% load i18n %}
{% load design_tags %}

{% block title %}
    {% project_list_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'browser_title' %}
            {% with texts|get_translated_field:'browser_title' as titl %}
                {{ titl|safe }}
            {% endwith %}
        {% else %}
            {% trans 'Projecs' %}
        {% endif %}
    {% else %}
        {% trans 'Projecs' %}
    {% endif %}
{% endblock title %}

{% block title2 %}
    {% project_list_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'banner_big_text' %}
            {% with texts|get_translated_field:'banner_big_text' as titl %}
                <h1 class="banner-title-style">  {{ titl|safe }} </h1>
            {% endwith %}
        {% endif %}
    {% else %}
        <h1 class="banner-title-style"> {% trans 'Projecs' %} </h1>
    {% endif %}
{% endblock title2 %}

{% block top %}
    {% design_settings as design %}
    {% if design.top_navigation %}
        <p class="text-white link-nav">
            <a href="{% url 'pages:home' %}"> {% trans 'Home' %} </a>
            <span class="lnr lnr-arrow-right"></span>
            <a href="{% url 'pages:projects' %}"> {% trans 'Projects' %} </a>
        </p>
    {% endif %}
{% endblock top %}

{% block conteiner %}

    <!-- Start gallery Area -->
    <section class="gallery-area section-gap">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12 pb-20 header-text text-center">
                    {% project_list_texts as texts %}
                    {% if texts.active %}
                        {% if texts|get_translated_field:'big_page_title' or texts|get_translated_field:'small_page_title' %}
                            {% with texts|get_translated_field:'big_page_title' as big %}
                                <h1 class="mb-10 big-title-style">{{ texts.big_page_title|safe }}</h1>
                            {% endwith %}
                            {% with texts|get_translated_field:'small_page_title' as small %}
                                <div class="small-title-style">{{ small|safe }}</div>
                            {% endwith %}
                        {% endif %}
                    {% endif %}

                    {% category_settings as category_set %}
                    {% if category_set.project_category %}
                        <div class="col-md-12 pb-10 header-text text-center">
                            <div class="row pb-15 pt-30 justify-content-center ml-20 mr-20" style="float: none">
                                <a class="primary-btn mt-30 ml-10" href="{% url 'pages:projects' %}">{% trans 'All Projects' %}</a>
                                {% project_categories as categories %}
                                {% for categ in categories %}
                                    <a class="primary-btn mt-30 ml-10" href="{{ categ.get_absolute_url }}">{{ categ.title }}</a>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="col-md-12 pb-10 header-text text-center">
                            <h3 class="pb-15 pt-30">
                                {% if category %}
                                    <div style="text-align: center">{% trans 'Category' %}: {{ category.title }}</div>
                                {% else %}
                                    <div style="text-align: center">{% trans 'All Projects' %}:</div>
                                {% endif %}
                            </h3>
                        </div>
                    {% endif %}
                </div>

                {% for pr in project_list %}
                    <div class="row">
                        {% with pr.0 as project %}
                            {% include 'include/pages/projects8.html' %}
                        {% endwith %}
                        {% if pr.1 %}
                            {% with pr.1 as project %}
                                {% include 'include/pages/projects4.html' %}
                            {% endwith %}
                        {% endif %}
                    </div>
                    <div class="row">
                        {% if pr.2 %}
                            {% with pr.2 as project %}
                                {% include 'include/pages/projects4.html' %}
                            {% endwith %}
                        {% endif %}
                        {% if pr.3 %}
                            {% with pr.3 as project %}
                                {% include 'include/pages/projects8.html' %}
                            {% endwith %}
                        {% endif %}
                    </div>
                    <div class="row">
                        {% if pr.4 %}
                            {% with pr.4 as project %}
                                {% include 'include/pages/projects8.html' %}
                            {% endwith %}
                        {% endif %}
                        {% if pr.5 %}
                            {% with pr.5 as project %}
                                {% include 'include/pages/projects4.html' %}
                            {% endwith %}
                        {% endif %}
                    </div>

                {% endfor %}
                {% include 'include/pagination.html' %}
        </div>
    </section>
    <!-- End gallery Area -->

{% endblock conteiner %}

app/templates/pages/service_detail.html
{% extends 'base.html' %}
{% load parler_tags %}
{% load thumbnail %}

{% load static %}
{% load i18n %}
{% load design_tags %}

{% block title %}
    {% service_detail_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'browser_title' %}
            {% with texts|get_translated_field:'browser_title' as titl %}
                {{ titl|safe }} {% if texts.add_name %} "{{ service.title }}" {% endif %}
            {% endwith %}
        {% else %}
            {% trans 'Service' %}
        {% endif %}
    {% else %}
        {% trans 'Service' %}
    {% endif %}
{% endblock title %}

{% block title2 %}
    {% service_detail_texts as texts %}
    {% if texts.active %}
        {% if texts|get_translated_field:'banner_big_text' %}
            {% with texts|get_translated_field:'banner_big_text' as titl %}
                <h1 class="banner-title-style">  {{ titl|safe }} {% if texts.add_name %} "{{ service.title }}" {% endif %} </h1>
            {% endwith %}
        {% endif %}
    {% else %}
        <h1 class="banner-title-style"> {% trans 'Service' %} </h1>
    {% endif %}
{% endblock title2 %}

{% block top %}
    {% design_settings as design %}
    {% if design.top_navigation %}
        <p class="text-white link-nav">
            <a href="{% url 'pages:home' %}"> {% trans 'Home' %} </a>
            <span class="lnr lnr-arrow-right"></span>
            <a href="{% url 'pages:service_list' %}"> {% trans 'Service' %} </a>
        </p>
    {% endif %}
{% endblock top %}


{% block conteiner %}
    <section class="service-area section-gap" id="service">
        <div class="container">
            <div class="col-md-12 mb-20 header-text text-center">
                <h1 class="mb-10 big-title-style">{{ service.title }}</h1>
                {% service_detail_texts as texts %}
                {% if texts.active %}
                    {% if texts|get_translated_field:'small_page_title' %}
                        {% with texts|get_translated_field:'small_page_title' as small %}
                            <div class="small-title-style">{{ small|safe }}</div>
                        {% endwith %}
                    {% endif %}
                {% endif %}

                <div class="mb-15 center">
                    {% with service.image as image %}
                        {% if image %}
                            {% thumbnail image "1045x300" crop='center' as img %}
                                <img class="img-fluid d-block" style="border-radius: 10px"  src="{{ img.url }}" height="1045" alt="">
                            {% endthumbnail %}
                        {% endif %}
                    {% endwith %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <blockquote class="generic-blockquote">
                            <p class="main-style">{{ service.short_description|safe }}</p>
                            <p class="main-style">{{ service.description|safe }}</p>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock conteiner %}